#!/usr/bin/env bash

cd -;
cd ${ZIP_DIR};
git config --global user.name "Adek Maulana"
git config --global user.email "adek@techdro.id"

git add -f .
git remote rm origin
git remote add origin https://adekmaulana:$GITHUB_API_KEY@github.com/techdro-id/zip.git
git add -f
git commit -m "Stormguard: $TRAVIS_BUILD_NUMBER ${VERSION} $ZIPNAME"
git push -fq origin master
